(function(fb,parentModule){var Module={};Module.arguments=[];Module.cleanups=[];var gb=0;var STACKTOP=getMemory(parentModule["TOTAL_STACK"]);assert(STACKTOP%8==0);var STACK_MAX=STACKTOP+parentModule["TOTAL_STACK"];Module.cleanups.push(function(){parentModule["_free"](STACKTOP);parentModule["_free"](gb)});gb=alignMemory(getMemory(200+4),4||1);for(var i=gb;i<gb+200;++i)HEAP8[i]=0;allocate([10,72,101,108,108,32,83,117,98,70,117,110,99,33,33,0],"i8",ALLOC_NONE,gb);function _printf(){return parentModule["_printf"].apply(null,arguments)}var ASSERTIONS=false;var asmGlobalArg={"Math":Math,"Int8Array":Int8Array,"Int16Array":Int16Array,"Int32Array":Int32Array,"Uint8Array":Uint8Array,"Uint16Array":Uint16Array,"Uint32Array":Uint32Array,"Float32Array":Float32Array,"Float64Array":Float64Array,"NaN":NaN,Infinity:Infinity};var asmLibraryArg={"a":abort,"b":setTempRet0,"c":getTempRet0,"d":_printf,"e":tempDoublePtr,"f":gb,"g":fb,"h":STACKTOP,"i":STACK_MAX};// EMSCRIPTEN_START_ASM
var asm=(/** @suppress {uselessCode} */ function(global,env,buffer) {
"use asm";var a=new global.Int8Array(buffer),b=new global.Int16Array(buffer),c=new global.Int32Array(buffer),d=new global.Uint8Array(buffer),e=new global.Uint16Array(buffer),f=new global.Uint32Array(buffer),g=new global.Float32Array(buffer),h=new global.Float64Array(buffer),i=env.e|0,j=env.f|0,k=env.g|0,l=env.h|0,m=env.i|0,n=0,o=0,p=0,q=0,r=0,s=0,t=0,u=0.0,v=global.NaN,w=global.Infinity,x=global.Math.floor,y=global.Math.abs,z=global.Math.sqrt,A=global.Math.pow,B=global.Math.cos,C=global.Math.sin,D=global.Math.tan,E=global.Math.acos,F=global.Math.asin,G=global.Math.atan,H=global.Math.atan2,I=global.Math.exp,J=global.Math.log,K=global.Math.ceil,L=global.Math.imul,M=global.Math.min,N=global.Math.max,O=global.Math.clz32,P=env.a,Q=env.b,R=env.c,S=env.d,T=0.0;
// EMSCRIPTEN_START_FUNCS
function U(a){a=a|0;var b=0;b=l;l=l+a|0;l=l+15&-16;return b|0}function V(){return l|0}function W(a){a=a|0;l=a}function X(){var a=0;a=l;l=l+16|0;S(j+0|0,a|0)|0;l=a;return}

// EMSCRIPTEN_END_FUNCS
return{_fTestExtFunc:X,stackAlloc:U,stackRestore:W,stackSave:V}})


// EMSCRIPTEN_END_ASM
(asmGlobalArg,asmLibraryArg,buffer);var _fTestExtFunc=Module["_fTestExtFunc"]=asm["_fTestExtFunc"];var NAMED_GLOBALS={};for(var named in NAMED_GLOBALS){Module["_"+named]=gb+NAMED_GLOBALS[named]}Module["NAMED_GLOBALS"]=NAMED_GLOBALS;parentModule["registerFunctions"]([],Module);if(runtimeInitialized){callRuntimeCallbacks(__ATPRERUN__);callRuntimeCallbacks(__ATINIT__)}return Module});if(typeof window==="object"&&(typeof ENVIRONMENT_IS_PTHREAD==="undefined"||!ENVIRONMENT_IS_PTHREAD)){var emrun_register_handlers=function(){var emrun_num_post_messages_in_flight=0;var emrun_should_close_itself=false;var postExit=function(msg){var http=new XMLHttpRequest;http.open("POST","stdio.html",false);http.send(msg);try{window.close()}catch(e){}};var post=function(msg){var http=new XMLHttpRequest;++emrun_num_post_messages_in_flight;http.onreadystatechange=function(){if(http.readyState==4){if(--emrun_num_post_messages_in_flight==0&&emrun_should_close_itself)postExit("^exit^"+EXITSTATUS)}};http.open("POST","stdio.html",true);http.send(msg)};if(document.URL.search("localhost")!=-1||document.URL.search(":6931/")!=-1){var emrun_http_sequence_number=1;var prevPrint=out;var prevErr=err;Module["addOnExit"](function(){if(emrun_num_post_messages_in_flight==0)postExit("^exit^"+EXITSTATUS);else emrun_should_close_itself=true});out=function(text){post("^out^"+emrun_http_sequence_number+++"^"+encodeURIComponent(text));prevPrint(text)};err=function(text){post("^err^"+emrun_http_sequence_number+++"^"+encodeURIComponent(text));prevErr(text)};var tryToSendPageload=function(){try{post("^pageload^")}catch(e){setTimeout(tryToSendPageload,50)}};tryToSendPageload()}};if(typeof Module!=="undefined"&&typeof document!=="undefined")emrun_register_handlers()}

